# Generated by Django 3.2.7 on 2021-10-08 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20211006_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reweet_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweeted', to='post.post'),
        ),
    ]
