# Generated by Django 3.2.7 on 2021-10-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_reweet_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reweet_post',
            new_name='repost_parent',
        ),
    ]
