# Generated by Django 3.2.7 on 2021-10-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_reweet_post_post_repost_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='repost_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposted', to='post.post'),
        ),
    ]
